format long; clc; clear; close;

% pain
for k = 1:1000 - 1
    disp(1/k)
end

% ... I can't even read cycles that long on the screen...
% and even if I can make it show more digits, what if the
% answer is in the hundreds? ... ... ... ... ... ... ... ... ...
% well, atleast I struggled with the problem...
% I'll leave this for now...
